NAME           = sdsc-beast_$(VERSION)
VERSION        = 1.8.1
RELEASE        = 6
PKGROOT        = /opt/beast/$(VERSION)

SRC_SUBDIR     = beast

SOURCE_NAME    = BEAST
SOURCE_SUFFIX  = tgz
SOURCE_VERSION = $(VERSION)
SOURCE_PKG     = $(SOURCE_NAME)v$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR     = $(SOURCE_PKG:%.$(SOURCE_SUFFIX)=%)

TGZ_PKGS    = $(SOURCE_PKG)

RPM.EXTRAS     = AutoReq:No
