#%Module1.0
module-whatis "beast"
module-whatis "Version: VERSION"
module-whatis "Description: beast"
module-whatis "Compiler: ROLLCOMPILER"
module load beagle/3.1.2
set     beasthome       /opt/beast/VERSION
setenv  BEAST           $beasthome
setenv  BEAST_HOME      $beasthome
setenv  BEAST_LIB       $beasthome/lib
append-path     PATH    $beasthome/bin
append-path     LD_LIBRARY_PATH $beasthome/lib
append-path     CLASSPATH       $beasthome/lib/beast.jar
append-path     CLASSPATH       $beasthome/lib/beauti.jar
